import type { PlanData } from "@/components/plan/PlanDocument";
import type { TaskStatus } from "@/lib/roadmap";

export type PlanItemGroup = "goal" | "d90" | "milestone" | "funding";

export interface PlanItem {
  key: string;
  group: PlanItemGroup;
  title: string;
  detail?: string;
  /** Extra context line (horizon, effort, target month, target amount). */
  meta?: string;
  status: TaskStatus;
  note?: string;
  completedAt?: string | null;
  updatedAt?: string | null;
  index: number;
  /** True when the user created this item (not generated by the plan). */
  custom?: boolean;
  /** True when a generated item's text has been edited by the user. */
  edited?: boolean;
  /** True when the item no longer exists in the current generated plan. */
  archived?: boolean;
}

export interface PlanProgressRow {
  task_key: string;
  task_label?: string | null;
  status?: string | null;
  completed?: boolean;
  completed_at?: string | null;
  updated_at?: string | null;
}

export const PLAN_ITEM_PREFIX = "plan";

export function planItemKey(group: PlanItemGroup, index: number) {
  return `${PLAN_ITEM_PREFIX}:${group}:${index}`;
}

export function planNoteKey(group: PlanItemGroup, index: number) {
  return `${PLAN_ITEM_PREFIX}:${group}note:${index}`;
}

export function planEditKey(group: PlanItemGroup, index: number) {
  return `${PLAN_ITEM_PREFIX}:${group}edit:${index}`;
}

export function planCustomKey(group: PlanItemGroup, id: string) {
  return `${PLAN_ITEM_PREFIX}:${group}custom:${id}`;
}

export interface PlanItemPayload {
  title?: string;
  detail?: string;
  meta?: string;
  hidden?: boolean;
}

export function parsePayload(label?: string | null): PlanItemPayload | null {
  if (!label) return null;
  try {
    const parsed = JSON.parse(label);
    if (parsed && typeof parsed === "object") return parsed as PlanItemPayload;
  } catch {
    /* not a payload row */
  }
  return null;
}

export function encodePayload(payload: PlanItemPayload) {
  return JSON.stringify(payload);
}

function toStatus(row?: PlanProgressRow): TaskStatus {
  if (!row) return "not_started";
  if (row.status === "in_progress" || row.status === "completed" || row.status === "not_started") {
    return row.status;
  }
  return row.completed ? "completed" : "not_started";
}

/** Which 30-day window a 90-day action item belongs to. */
export function windowForStep(step: number, total: number) {
  const perWindow = Math.max(1, Math.ceil(total / 3));
  const idx = Math.min(2, Math.floor((step - 1) / perWindow));
  return (["Days 1–30", "Days 31–60", "Days 61–90"] as const)[idx];
}

interface DeriveArgs {
  planData?: PlanData | null;
  progress: PlanProgressRow[];
  overrides?: Record<string, TaskStatus>;
  noteOverrides?: Record<string, string>;
  /** Local, optimistic edits/custom items keyed by their storage key. */
  payloadOverrides?: Record<string, PlanItemPayload | null>;
}

export interface PlanItemSets {
  goals: PlanItem[];
  actions: PlanItem[];
  milestones: PlanItem[];
  funding: PlanItem[];
  all: PlanItem[];
  archived: PlanItem[];
}

export function derivePlanItems({
  planData,
  progress,
  overrides = {},
  noteOverrides = {},
  payloadOverrides = {},
}: DeriveArgs): PlanItemSets {
  const byKey = new Map<string, PlanProgressRow>();
  for (const row of progress) byKey.set(row.task_key, row);

  const payloadFor = (key: string): PlanItemPayload | null => {
    if (key in payloadOverrides) return payloadOverrides[key];
    return parsePayload(byKey.get(key)?.task_label);
  };

  const build = (group: PlanItemGroup, index: number, title: string, detail?: string, meta?: string): PlanItem => {
    const key = planItemKey(group, index);
    const row = byKey.get(key);
    const override = payloadFor(planEditKey(group, index));
    return {
      key,
      group,
      index,
      title: override?.title ?? title,
      detail: override?.detail ?? detail,
      meta: override?.meta ?? meta,
      edited: !!override,
      status: overrides[key] ?? toStatus(row),
      note: noteOverrides[planNoteKey(group, index)] ?? byKey.get(planNoteKey(group, index))?.task_label ?? "",
      completedAt: row?.completed_at ?? null,
      updatedAt: row?.updated_at ?? null,
    };
  };

  /** User-created items for a group, in creation order. */
  const customFor = (group: PlanItemGroup, offset: number): PlanItem[] => {
    const prefix = `${PLAN_ITEM_PREFIX}:${group}custom:`;
    const keys = new Set<string>();
    for (const row of progress) if (row.task_key.startsWith(prefix)) keys.add(row.task_key);
    for (const key of Object.keys(payloadOverrides)) if (key.startsWith(prefix)) keys.add(key);

    return [...keys]
      .map((key, i) => {
        const payload = payloadFor(key);
        if (!payload || payload.hidden) return null;
        const row = byKey.get(key);
        return {
          key,
          group,
          index: offset + i,
          title: payload.title || "Untitled",
          detail: payload.detail,
          meta: payload.meta,
          custom: true,
          status: overrides[key] ?? toStatus(row),
          note: "",
          completedAt: row?.completed_at ?? null,
          updatedAt: row?.updated_at ?? null,
        } as PlanItem;
      })
      .filter((i): i is PlanItem => !!i);
  };

  const visible = (items: PlanItem[]) =>
    items.filter((i) => !payloadFor(planEditKey(i.group, i.index))?.hidden);

  const sections = planData?.sections;

  const generatedGoals = (sections?.goals_snapshot?.goals ?? []).map((g, i) =>
    build(
      "goal",
      i,
      g.label,
      g.why_it_matters,
      [g.priority ? `${g.priority} goal` : null, g.horizon, g.target_amount].filter(Boolean).join(" · ") || undefined,
    ),
  );
  const goals = [...visible(generatedGoals), ...customFor("goal", generatedGoals.length)];

  const actionItems = sections?.action_plan_90day?.items ?? [];
  const generatedActions = actionItems.map((a, i) =>
    build("d90", i, a.text, undefined, [windowForStep(a.step ?? i + 1, actionItems.length), a.effort].filter(Boolean).join(" · ")),
  );
  const actions = [...visible(generatedActions), ...customFor("d90", generatedActions.length)];

  const generatedMilestones = (sections?.roadmap?.milestones ?? []).map((m, i) =>
    build("milestone", i, m.description, undefined, m.month),
  );
  const milestones = [...visible(generatedMilestones), ...customFor("milestone", generatedMilestones.length)];

  const generatedFunding = (sections?.funding_opportunities?.items ?? []).map((f, i) =>
    build("funding", i, f.type, f.description),
  );
  const funding = [...visible(generatedFunding), ...customFor("funding", generatedFunding.length)];

  // Rows that point at generated slots which no longer exist (plan was regenerated shorter).
  const generatedCounts: Record<PlanItemGroup, number> = {
    goal: generatedGoals.length,
    d90: generatedActions.length,
    milestone: generatedMilestones.length,
    funding: generatedFunding.length,
  };
  const archived: PlanItem[] = [];
  for (const row of progress) {
    const m = row.task_key.match(/^plan:(goal|d90|milestone|funding):(\d+)$/);
    if (!m) continue;
    const group = m[1] as PlanItemGroup;
    const index = Number(m[2]);
    if (index < generatedCounts[group]) continue;
    const label = row.task_label?.trim();
    if (!label) continue;
    archived.push({
      key: row.task_key,
      group,
      index,
      title: label,
      status: overrides[row.task_key] ?? toStatus(row),
      archived: true,
      completedAt: row.completed_at ?? null,
      updatedAt: row.updated_at ?? null,
    });
  }

  return {
    goals,
    actions,
    milestones,
    funding,
    archived,
    all: [...goals, ...actions, ...milestones, ...funding],
  };
}

export function countDone(items: PlanItem[]) {
  return items.filter((i) => i.status === "completed").length;
}

export function pct(items: PlanItem[]) {
  if (items.length === 0) return 0;
  return Math.round((countDone(items) / items.length) * 100);
}